version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: tnn-db
      POSTGRES_USER: tnn
      POSTGRES_PASSWORD: tnn-password
    ports:
      - "5432:5432"
    volumes:
      - C:\dev\data\postgres:/var/lib/postgresql/data
  service-finance:
    image: service-finance:1.0-SNAPSHOT
    container_name: service_finance
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: tnn-db
      DB_USERNAME: tnn
      DB_PASSWORD: tnn-password
    ports:
      - "8085:8080"
    depends_on:
      - postgres-db