version: '3.8'
services:
  postgres-db:
    image: ${DB_IMAGE}:${DB_VERSION}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_DATA_MOUNT}:/var/lib/postgresql/data
#  service-api-gateway:
#    image: ${SERVICE_IMAGE_API_GATEWAY}:${SERVICE_VERSION_API_GATEWAY}
#    container_name: service-api-gateway
#    environment:
#      DB_HOST: postgres-db
#      DB_PORT: ${DB_PORT}
#      DB_NAME: ${DB_NAME}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      SERVICE_REGISTRATION_HOST: ${SERVICE_REGISTRATION_HOST}
#      SERVICE_REGISTRATION_PORT: ${SERVICE_REGISTRATION_PORT}
#      SERVICE_FINANCE_HOST: ${SERVICE_FINANCE_HOST}
#      SERVICE_FINANCE_PORT: ${SERVICE_FINANCE_PORT}
#    ports:
#      - "80:8080"
#    depends_on:
#      - postgres-db
#  service-registration:
#    image: ${SERVICE_IMAGE_REGISTRATION}:${SERVICE_VERSION_REGISTRATION}
#    container_name: service-registration
#    environment:
#      DB_HOST: postgres-db
#      DB_PORT: ${DB_PORT}
#      DB_NAME: ${DB_NAME}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "${SERVICE_REGISTRATION_PORT}:8080"
#    depends_on:
#      - postgres-db
  service-finance:
    image: ${SERVICE_IMAGE_FINANCE}:${SERVICE_VERSION_FINANCE}
    container_name: service-finance
    environment:
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${SERVICE_FINANCE_PORT}:8080"
    depends_on:
      - postgres-db